import { test, expect } from "@playwright/test";

test.describe("Confirmação Pública", () => {
  test("deve exibir erro para token inválido", async ({ page }) => {
    await page.goto("/confirmar/token-invalido-123");

    await expect(page.getByText("Link inválido")).toBeVisible({ timeout: 10000 });
  });

  test("deve exibir dados de movimentação com token válido", async ({
    page,
  }) => {
    // This test depends on the seed data. The seed creates movimentações with
    // tokens generated by cuid(). We navigate to check the UI renders correctly
    // for known states (expired, already confirmed).
    // For a complete E2E, we'd need to query the DB for a valid token.
    // Here we verify the confirmation layout renders.
    await page.goto("/confirmar/any-token");
    await expect(page.getByText("SIMAP")).toBeVisible();
  });
});
